// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.5

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type DownloadHTTPServer interface {
	GetDownloadURL(context.Context, *GetDownloadRequest) (*GetDownloadReply, error)
}

func RegisterDownloadHTTPServer(s *http.Server, srv DownloadHTTPServer) {
	r := s.Route("/")
	r.GET("/download/{key}", _Download_GetDownloadURL0_HTTP_Handler(srv))
}

func _Download_GetDownloadURL0_HTTP_Handler(srv DownloadHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDownloadRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.download.v1.Download/GetGame")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDownloadURL(ctx, req.(*GetDownloadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDownloadReply)
		return ctx.Result(200, reply)
	}
}

type DownloadHTTPClient interface {
	GetDownloadURL(ctx context.Context, req *GetDownloadRequest, opts ...http.CallOption) (rsp *GetDownloadReply, err error)
}

type DownloadHTTPClientImpl struct {
	cc *http.Client
}

func NewDownloadHTTPClient(client *http.Client) DownloadHTTPClient {
	return &DownloadHTTPClientImpl{client}
}

func (c *DownloadHTTPClientImpl) GetDownloadURL(ctx context.Context, in *GetDownloadRequest, opts ...http.CallOption) (*GetDownloadReply, error) {
	var out GetDownloadReply
	pattern := "/download/{key}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.download.v1.Download/GetGame"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
