// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"game/internal/biz"
	"game/internal/conf"
	"game/internal/data"
	"game/internal/server"
	"game/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDataBase(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	client, err := data.NewCache(confData)
	if err != nil {
		return nil, nil, err
	}
	objectStorage, err := data.NewObjectStorage(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, db, client, objectStorage, logger)
	if err != nil {
		return nil, nil, err
	}
	gameRepo := data.NewGameRepo(dataData, logger)
	gameUseCase := biz.NewGameUseCase(gameRepo, logger)
	gameService := service.NewGameService(gameUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, gameService, logger)
	grpcServer := server.NewGRPCServer(confServer, gameService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
